common/models/YahooAuctions.php
<?php
/**
 * Created by PhpStorm.
 * User: anilkumar
 * Date: 10/05/16
 * Time: 4:27 PM
 */

namespace common\models;

use Yii;
use \common\components\TBase;
use common\components\TCurrencyConvertor;
//http://tiger4th.com/auc/computer/?q=&s=cbids&o=d&t=1&c=23336
//http://developer.yahoo.co.jp/webapi/auctions/
//http://tiger4th.com/auc/computer/?q=&s=cbids&o=d&t=1&n=3
class YahooAuctions extends TCurrencyConvertor
{
    /**
     * @var
     */
    public $YahooAction;
    public $ITEM_SEARCH_API_URL;
    public $ITEM_DETAIL_API_URL;
    public $APIID;
    public $AUCTION_URL;

    function __construct() {
        $this->AUCTION_URL = 'https://auctions.yahooapis.jp/AuctionWebService/V2/';
        $this->ITEM_SEARCH_API_URL = TBase::TanukiSetting('YAHOO_ITEM_SEARCH_API_URL');
        $this->ITEM_DETAIL_API_URL = TBase::TanukiSetting('YAHOO_ITEM_DETAIL_API_URL');
        $this->APIID = TBase::TanukiSetting('YAHOO_API_ID');
    }

    public function urlencode_RFC3986($str)
    {
        return str_replace('%7E', '~', rawurlencode($str));
    }

    public function productsListing($params){

        $params = array_merge($params,['appid'  =>  $this->APIID]);
        $api_url = $this->AUCTION_URL.'categoryLeaf?'.Http_build_query($params);
        $category = simplexml_load_file($api_url);
        return $category = json_decode(json_encode($category), true);
    }

    public function productsSellerListing($params){

        $params = array_merge($params,['appid'  =>  $this->APIID]);
        $api_url = $this->AUCTION_URL.'sellingList?'.Http_build_query($params);
        $category = simplexml_load_file($api_url);
        return $category = json_decode(json_encode($category), true);
    }

    public function auctionSearch($params){

        $params = array_merge($params,['appid'  =>  $this->APIID]);
        $api_url = $this->AUCTION_URL.'search?'.Http_build_query($params);
        $category = simplexml_load_file($api_url);
        return $category = json_decode(json_encode($category), true);
    }

    /**
     * @param $auctionID
     * @param string $response
     */
    public function productsDetail($auctionID, $response = 'large')
    {
        $params = Array (
            'auctionID'  =>  $auctionID,
            'responsegroup'  =>  $response
        );
        $ch = curl_init ( $this->AUCTION_URL.'php/auctionItem?' . Http_build_query ( $params ));
        Curl_setopt_array ( $ch , Array (
            CURLOPT_RETURNTRANSFER =>  True ,
            CURLOPT_USERAGENT       =>  "Yahoo AppID: $this->APIID"
        ));

        $Result = Curl_exec ( $ch );
        curl_close ( $ch );

        return $this->YahooAction = unserialize($Result);
    }

    /**
     * @param $ID
     * @return mixed
     */
    public function getCategories($ID) {
        $params = Array (
            'category'  =>  $ID,
            'responsegroup'  =>  'large'
        );

        $params = array_merge($params,['appid'  =>  $this->APIID]);
        $api_url = $this->AUCTION_URL.'categoryTree?'.Http_build_query($params);
        $category = simplexml_load_file($api_url);
        return $category = json_decode(json_encode($category), true);

    }

    /**
     * @param $auctionID
     * @param string $response
     * @return mixed
     */
    public function productsDetailForFavorite($auctionID, $response = 'large'){
        $params = Array (
            'auctionID'  =>  $auctionID,
            'responsegroup'  =>  $response
        );
        $ch = curl_init ( $this->AUCTION_URL.'php/auctionItem?' . Http_build_query ( $params ));
        Curl_setopt_array ( $ch , Array (
            CURLOPT_RETURNTRANSFER =>  True ,
            CURLOPT_USERAGENT       =>  "Yahoo AppID: $this->APIID"
        ));

        $Result = Curl_exec ( $ch );
        curl_close ( $ch );

        return unserialize($Result);
    }

    /**
     * @param bool $imageUrl
     * @return string
     */
    public function getImage($imageUrl = false) {
	    $img = '';
        if (
            isset($this->YahooAction['ResultSet']['Result']['Img']['Image1']) &&
            !empty($this->YahooAction['ResultSet']['Result']['Img']['Image1'])
        ) {
            if ($imageUrl) {
                $img = $this->YahooAction['ResultSet']['Result']['Img']['Image1'];
            } else {
	            $img = Yii::$app->formatter->asImage($this->YahooAction['ResultSet']['Result']['Img']['Image1'],['width'=>'70','height'=>'70']);
            }
            return $img;
        } else {
            return  $img;
        }
    }

    /**
     * @return string
     */
    public function getPrice() {
        if (isset($this->YahooAction['ResultSet']['Result']['Price'])) {
            if(isset($this->YahooAction['ResultSet']['Result']['TaxinPrice'])) {
                return $this->convert($this->YahooAction['ResultSet']['Result']['TaxinPrice'],'JPY','JPY');
            } else {
                return $this->convert($this->YahooAction['ResultSet']['Result']['Price'],'JPY','JPY');
            }
        }
    }

    /**
     * @return string
     */
    public function getTimeLeft(){
        $now = new \DateTime();
        $future_date = new \DateTime($this->YahooAction['ResultSet']['Result']['EndTime']);
        $interval = $future_date->diff($now);
        return $interval->format("%ad: %hh: %im: %ss");
    }

    /**
     * @return string
     */
    public function getTopBidder() {
        if (
            isset($this->YahooAction['ResultSet']['Result']['HighestBidders'])  &&
            isset($this->YahooAction['ResultSet']['Result']['HighestBidders']['Bidder']['Id'])
        ) {
            return $this->YahooAction['ResultSet']['Result']['HighestBidders']['Bidder']['Id'];
        } else {
            return '-';
        }
    }

    public function myAuctionsList($auctionID, $response = 'large'){
        $params = Array (
            'auctionID'  =>  $auctionID,
            'responsegroup'  =>  $response
        );
        $ch = curl_init ( $this->AUCTION_URL.'php/auctionItem?' . Http_build_query ( $params ));
        Curl_setopt_array ( $ch , Array (
            CURLOPT_RETURNTRANSFER =>  True ,
            CURLOPT_USERAGENT       =>  "Yahoo AppID: $this->APIID"
        ));

        $Result = Curl_exec ( $ch );
        curl_close ( $ch );

        return unserialize($Result);
    }
}

frontend/controllers/YahooAuctionsController.php
<?php
namespace frontend\controllers;

use common\models\User;
use common\models\UserAuctionBlockedAmount;
use common\models\UserAuctions;
use common\components\TBase;
use Yii;
use \common\models\YahooAuctions;
use \common\models\Category;
use \common\components\MailCamp;
use yii\helpers\Html;

/**
 * Site controller
 */
class YahooAuctionsController extends BaseController
{
    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        \Yii::$app->view->registerMetaTag([
            'name' => 'google',
            'content' => 'notranslate'
        ]);
        $this->layout = 'main';
        $categories = Category::find()->where(['status'=>1,'shop'=>'yahoo_auctions'])->orderBy('serial_no')->all();
        return $this->render('categories',['categories'=>$categories]);
    }

    /**
     * @return string
     */
    public function actionList()
    {
	    $cid = Yii::$app->request->get('cid');
	    if ($cid) {
		    if ($model = Category::findOne( $cid )) {
			    \Yii::$app->view->title = $model->title_en;
			    \Yii::$app->view->registerMetaTag( [
				    'name'    => 'title',
				    'content' => $model->meta_title,
			    ] );
			    \Yii::$app->view->registerMetaTag( [
				    'name'    => 'description',
				    'content' => $model->meta_description,
			    ] );
			    \Yii::$app->view->registerMetaTag( [
				    'name'    => 'keywords',
				    'content' => $model->meta_keywords,
			    ] );
		    }
	    }
        $model  = new YahooAuctions();
        $id = (
                Yii::$app->request->get('cid') &&
                (
                    Yii::$app->request->get('cid') != 'All' ||
                    Yii::$app->request->get('cid') != 0
                )
            ) ? Yii::$app->request->get('cid') : false;
        $page   = (int)Yii::$app->request->get('page') ? Yii::$app->request->get('page') : 1;
        $paramsVar = ['page'=>$page];
        $category = false;

        $params = array_merge([Yii::$app->controller->id.'/'.Yii::$app->controller->action->id],['page'=>1]);

        if ($id) {
            $category = Category::findOne(['ref_id'=>$id]);
            $paramsVar = array_merge($paramsVar,['category'=>$id]);
            $params = array_merge($params,['cid'=>$id]);
        }

        if (Yii::$app->request->get('s')) {
            $paramsVar = array_merge($paramsVar, ['query' => Yii::$app->request->get('s')]);
            $params = array_merge($params,['cid'=>$id,'s' => Yii::$app->request->get('s')]);

        }

        if (Yii::$app->request->get('aucminprice')) {
            $paramsVar['aucminprice'] = Yii::$app->request->get('aucminprice');
            $params = array_merge($params, ['aucminprice' => $paramsVar['aucminprice']]);
        }

        if (Yii::$app->request->get('aucmaxprice')) {
            $paramsVar['aucmaxprice'] = Yii::$app->request->get('aucmaxprice');
            $params = array_merge($params, ['aucmaxprice' => $paramsVar['aucmaxprice']]);
        }

        if (Yii::$app->request->get('aucmin_bidorbuy_price')) {
            $paramsVar['aucmin_bidorbuy_price'] = Yii::$app->request->get('aucmin_bidorbuy_price');
            $params = array_merge($params, ['aucmin_bidorbuy_price' => $paramsVar['aucmin_bidorbuy_price']]);
        }

        if (Yii::$app->request->get('aucmax_bidorbuy_price')) {
            $paramsVar['aucmax_bidorbuy_price'] = Yii::$app->request->get('aucmax_bidorbuy_price');
            $params = array_merge($params, ['aucmax_bidorbuy_price' => $paramsVar['aucmax_bidorbuy_price']]);
        }

        $paramsVar['sort'] = 'end'; //current price
        $paramsVar['order'] = 'a'; //current price
        $paramsVar['ranking'] = 'popular'; // order ascending order

        if (Yii::$app->request->get('sort')){
            $paramsVar['sort'] = Yii::$app->request->get('sort');
            $params = array_merge($params, ['sort' => $paramsVar['sort']]);
        }

        if (Yii::$app->request->get('order')){
            $paramsVar['order'] = Yii::$app->request->get('order');
            $params = array_merge($params, ['order' => $paramsVar['order']]);
        }

        if (Yii::$app->request->get('ranking')){
            $paramsVar['ranking'] = Yii::$app->request->get('ranking');
            $params = array_merge($params, ['ranking' => $paramsVar['ranking']]);
        }

        if (Yii::$app->request->get('store') && Yii::$app->request->get('store') != '0'){
            $paramsVar['store'] = Yii::$app->request->get('store');
            $params = array_merge($params, ['store' => $paramsVar['store']]);
        }

        if (Yii::$app->request->get('item_status') && Yii::$app->request->get('item_status') != '0'){
            $paramsVar['item_status'] = Yii::$app->request->get('item_status');
            $params = array_merge($params, ['item_status' => $paramsVar['item_status']]);
        }

        if (Yii::$app->request->get('new')){
            $paramsVar['new'] = 1;
            $params = array_merge($params, ['new' => $paramsVar['new']]);
        }

        if (Yii::$app->request->get('freeshipping')){
            $paramsVar['freeshipping'] = 1;
            $params = array_merge($params, ['freeshipping' => $paramsVar['freeshipping']]);
        }

        if (Yii::$app->request->get('buynow')){
            $paramsVar['buynow'] = 1;
            $params = array_merge($params, ['buynow' => $paramsVar['buynow']]);
        }

        if (Yii::$app->request->get('thumbnail')){
            $paramsVar['thumbnail'] = 1;
            $params = array_merge($params, ['thumbnail' => $paramsVar['thumbnail']]);
        }

        if (Yii::$app->request->get('goodSellers')){
            $paramsVar['goodSellers'] = 1;
            $params = array_merge($params, ['goodSellers' => $paramsVar['goodSellers']]);
        }


        if (Yii::$app->request->get('search') || Yii::$app->request->get('s')) {
            $data = $model->auctionSearch($paramsVar);
        } else {
            $data = $model->productsListing($paramsVar);
        }
        if (Yii::$app->request->isAjax) {
            return $this->renderPartial(
                '_listing',
                ['data'=>$data,'category'=>$category,'param'=>$params,'TModel'=>$model]
            );
        }
        return $this->render(
            'listing',
            ['data'=>$data,'category'=>$category,'param'=>$params,'TModel'=>$model]
        );
    }

    /**
     * @return string
     */
    public function actionSellerList()
    {
        $model  = new YahooAuctions();
        $page   = (int)(isset($_REQUEST['page'])) ? $_REQUEST['page'] : 1;
        $paramsVar = ['page'=>$page];
        $category = false;

        $params = array_merge([Yii::$app->controller->id.'/'.Yii::$app->controller->action->id],['page'=>1]);

        if (Yii::$app->request->get('aucminprice')) {
            $paramsVar['aucminprice'] = Yii::$app->request->get('aucminprice');
            $params = array_merge($params, ['aucminprice' => $paramsVar['aucminprice']]);
        }

        if (Yii::$app->request->get('aucmaxprice')) {
            $paramsVar['aucmaxprice'] = Yii::$app->request->get('aucmaxprice');
            $params = array_merge($params, ['aucmaxprice' => $paramsVar['aucmaxprice']]);
        }

        if (Yii::$app->request->get('aucmin_bidorbuy_price')) {
            $paramsVar['aucmin_bidorbuy_price'] = Yii::$app->request->get('aucmin_bidorbuy_price');
            $params = array_merge($params, ['aucmin_bidorbuy_price' => $paramsVar['aucmin_bidorbuy_price']]);
        }

        if (Yii::$app->request->get('aucmax_bidorbuy_price')) {
            $paramsVar['aucmax_bidorbuy_price'] = Yii::$app->request->get('aucmax_bidorbuy_price');
            $params = array_merge($params, ['aucmax_bidorbuy_price' => $paramsVar['aucmax_bidorbuy_price']]);
        }

        $paramsVar['sort'] = 'score'; //current price
        $paramsVar['ranking'] = 'popular'; // order ascending order

        if (Yii::$app->request->get('sellerID')){
            $paramsVar['sellerID'] = Yii::$app->request->get('sellerID');
            $params = array_merge($params, ['sellerID' => $paramsVar['sellerID']]);
        }

        if (Yii::$app->request->get('sort')){
            $paramsVar['sort'] = Yii::$app->request->get('sort');
            $params = array_merge($params, ['sort' => $paramsVar['sort']]);
        }

        if (Yii::$app->request->get('order')){
            $paramsVar['order'] = Yii::$app->request->get('order');
            $params = array_merge($params, ['order' => $paramsVar['order']]);
        }

        if (Yii::$app->request->get('ranking')){
            $paramsVar['ranking'] = Yii::$app->request->get('ranking');
            $params = array_merge($params, ['ranking' => $paramsVar['ranking']]);
        }

        if (Yii::$app->request->get('store') && Yii::$app->request->get('store') != '0'){
            $paramsVar['store'] = Yii::$app->request->get('store');
            $params = array_merge($params, ['store' => $paramsVar['store']]);
        }

        if (Yii::$app->request->get('item_status') && Yii::$app->request->get('item_status') != '0'){
            $paramsVar['item_status'] = Yii::$app->request->get('item_status');
            $params = array_merge($params, ['item_status' => $paramsVar['item_status']]);
        }

        if (Yii::$app->request->get('new')){
            $paramsVar['new'] = 1;
            $params = array_merge($params, ['new' => $paramsVar['new']]);
        }

        if (Yii::$app->request->get('freeshipping')){
            $paramsVar['freeshipping'] = 1;
            $params = array_merge($params, ['freeshipping' => $paramsVar['freeshipping']]);
        }

        if (Yii::$app->request->get('buynow')){
            $paramsVar['buynow'] = 1;
            $params = array_merge($params, ['buynow' => $paramsVar['buynow']]);
        }

        if (Yii::$app->request->get('thumbnail')){
            $paramsVar['thumbnail'] = 1;

frontend/views/yahoo-auctions/_listing.php
<?php
$model = new \common\components\TCurrencyConvertor;
use \common\components\TBase as LBL;
$cnt = 0;
$j = 1;
if (isset($data['Result']['Item']) && count($data['Result']['Item'])>2) {
    foreach($data['Result']['Item'] as $current){
        echo ($j == 1) ? '<div class="row '.$j.'">' : '';
        ?>

        <div class="col-sm-3 <?=$j?>">
            <div class="product-lst position-relative">
                <div class="loading hidden">
                    <?=LBL::_x('PLEASE_WAIT'); ?>
                </div>
                <?php if ($category) { ?>
                <a target="_blank" href="<?=\yii\helpers\Url::to(['detail','id'=>$current['AuctionID'],'cid'=>$category->ref_id])?>">
                    <?php } else { ?>
                    <a target="_blank" href="<?=\yii\helpers\Url::to(['detail','id'=>$current['AuctionID']])?>">
                        <?php } ?>
                        <div style="height: 150px;overflow: hidden;">
                            <?=Yii::$app->formatter->asImage($current['Image'],['class'=>"img-thumbnail"])?>
                        </div>
                        <div class="product-list-product translate"><?=$current['Title']; ?></div>
                    </a>
                    <h6>
                        <div class="clearfix">
                            <div class="col-md-6 text-center" style="border-right: 1px solid #dedede;">
	                            <?=LBL::_x('CURRENT_PRICE')?><br/>
                                <?php if (isset($current['CurrentPrice'])) { ?>
                                    <a class="amount" href="javascript:void(0)"
                                       data-usd="<?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','USD'); ?>"
                                       data-rub="<?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','RUB'); ?>"
                                       data-jpy="<?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','JPY'); ?>"
                                       data-cny="<?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','CNY'); ?>"
                                       data-eur="<?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','EUR'); ?>">
		                                <?=\common\models\CurrencyTable::convert((float)$current['CurrentPrice'],'JPY','JPY'); ?>
                                    </a>
                                <?php } else {
                                    echo '-';
                                }?>
                            </div>
                            <div class="col-md-6 text-center">
	                            <?=LBL::_x('BAYOUT_PRICE')?><br/>
                                <?php if (isset($current['BidOrBuy'])) { ?>
                                    <a class="amount" href="javascript:void(0)"
                                       data-usd="<?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','USD'); ?>"
                                       data-rub="<?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','RUB'); ?>"
                                       data-jpy="<?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','JPY'); ?>"
                                       data-cny="<?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','CNY'); ?>"
                                       data-eur="<?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','EUR'); ?>">
                                        <?=\common\models\CurrencyTable::convert((float)$current['BidOrBuy'],'JPY','JPY'); ?>
                                    </a>
                                <?php } else {
                                    echo '-';
                                }?>
                            </div>
                        </div>
                    </h6>
                    <div class="cate-list product-icon-listing">
                        <div class="clearfix">
                            <?php if ($category) { ?>
                                <div class="pull-left"><a target="_blank" class="detail-i" href="<?= \yii\helpers\Url::to(['detail','id'=>$current['AuctionID'],'cid'=>$category->ref_id])?>"></a></div>
                            <?php } else { ?>
                                <div class="pull-left"><a target="_blank" class="detail-i" href="<?= \yii\helpers\Url::to(['detail','id'=>$current['AuctionID']])?>"></a></div>
                            <?php } ?>
                            <div class="pull-left no-border"><a class="wish-i" data-href="<?= \yii\helpers\Url::toRoute(['favorite-product/create','shop'=>'yahoo_auction','code'=>$current['AuctionID']],true)?>"></a></div>
                        </div>
                    </div>
            </div>
        </div>
        <?php

        echo (($j % 4 == 0)) ? '</div><div class="row '.$j.'">' : '';
        $j++;
        $cnt++;

    } ?>
    </div>
<?php } else {
    echo "0";
    exit;
}
?>

frontend/views/yahoo-auctions/categories.php
<?php
    use yii\helpers\Html;
    use \common\components\TBase;
    $this->title = TBase::ShowLbl('YAHOO_CATEGORIES');
    $lang = TBase::CLang();
?>
<style>
     p a{color:#fff;}
     p a:hover{text-decoration: none;color:#fff;}
    .main-image{
        height:90px;
        overflow: hidden;
        margin-top: 15px;
        background: #888888;
    }
</style>
<div class="m_container rakuten yahoo-auction">
    <div class="container color-back">
        <div class="col-md-7 notranslate" style="margin-top: 4px;">
            <?=TBase::ShowLbl('YAHOO_AUCTION'); ?>
        </div>
        <div class="col-md-5 right-side-search">
            <form id="w1" action="<?=\yii\helpers\Url::to(['yahoo-auctions/detail'],true) ?>" method="GET">
                <!--                <div class="col-md-6 col-xs-10">-->
                <!--                    <label style="font-size: 14px;color:#333">--><?//=TBase::ShowLbl('SEARCH_AUCTION_LOT_ID') ?><!-- :</label>-->
                <!--                </div>-->
                <div class="col-md-offset-6 col-md-5 col-xs-10">
                    <input class="form-control" name="id" value="" type="text" placeholder="<?=TBase::ShowLbl('SEARCH_AUCTION_LOT_ID')?>">
                </div>
                <div class="col-md-1 col-xs-10 padding-left-0">
                    <input type="submit" class="yahoo_auction_search_btn search_btn" name="search" value="">
                </div>
                <input type="hidden" name="<?= Yii::$app->request->csrfParam; ?>" value="<?= Yii::$app->request->csrfToken; ?>" />
            </form>
        </div>
    </div>
</div>
<div class="container yahoo-auction notranslate main-image">
    <div class="row">
        <?=Html::a(Html::img('/uploads/yahooparts.jpg'),['/parts'],['target'=>'_blank'])?>
    </div>
</div>
<div class="container yahoo-auction notranslate">
    <div class="row marg-l0">
        <?php
        $j = 1;
        foreach ($categories as $cat) {
            if ($cat->parent_id == 0) {
                echo ($j == 1 || ($j % 4 == 0)) ? '<div class="row margin-bottom-20">' : ''; ?>
                <div class="col-md-3 col-sm-3 cat-list <?php echo $j.'_'.($j % 4); ?>">
                    <p>
                        <?=Html::a(($lang == 'en-US') ? $cat->title_en : $cat->title_ru,['yahoo-auctions/list','cid'=>$cat->ref_id]); ?>
                    </p>
                    <ul>
                        <?php
                        foreach ($categories as $catSub) {
                            if ($cat->id == $catSub->parent_id) {
                                $title = ($lang == 'en-US') ? $catSub->title_en : $catSub->title_ru;
                                echo '<li>'.Html::a($title,['yahoo-auctions/list','cid'=>$catSub->ref_id]).'</li>';
                            }
                        }
                        ?>
                    </ul>
                </div>
                <?php
                echo ($j %4 == 0 ) ? '</div>' : '';
                $j++;
            }
        }
        ?>
        <div class="clearfix"></div>
    </div>
</div>

frontend/views/yahoo-auctions/wait-page.php
<style>
    .text-center{
        font-size: 19px;
    }
    img {
        width: 58px;
    }
</style>
<section class="product-page">
    <div class="container">
        <div class="product-plug">
            <div class="row">
                <div class="form-group">
                    <div class="col-md-12 text-center">
                        <?=\yii\helpers\Html::img('@web/tnk/images/bx_loader.gif')?><br/>
                        <?=\common\components\TBase::_x('PLEASE_WAIT')?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>