backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use common\models\LoginForm;
use yii\filters\VerbFilter;

/**
 * Site controller
 */
class SiteController extends Controller
{
    public $layout = 'login';
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout','index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex()
    {
        $this->redirect(['dashboard/index']);
    }

    public function actionLogin()
    {
        $model = new LoginForm();
        $model->type = 'admin';
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['dashboard/index']);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->redirect(['site/login']);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\components\MailCamp;
use common\components\TBase;
use common\models\CurrencyTable;
use common\models\Labels;
use common\models\LabelsDetail;
use common\models\Page;
use common\models\ShippingMethodCalculationFinal;
use common\models\YahooAuctions;
use common\models\YahooConnect;
use common\models\YConnect;
use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use common\models\User;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\YahooOAuth2;
use yii\authclient\OAuth2;
use \common\models\ShippingCategory;
/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'user-validate', 'add-to-cart', 'lang-switch', 'product-shipping-cost', 'request-password-reset', 'paypal-testing', 'connect','category-shipping-cost','get-box','moneta-payment','moneta-payment-return'],
                'rules' => [
                    [
                        'actions' => ['signup', 'user-validate', 'lang-switch', 'captcha', 'product-shipping-cost', 'request-password-reset', 'paypal-testing', 'connect','category-shipping-cost','get-box','moneta-payment','moneta-payment-return'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'add-to-cart', 'lang-switch', 'product-shipping-cost', 'paypal-testing', 'stripe-testing', 'yahoo','won-list','category-shipping-cost','get-box','moneta-payment','moneta-payment-return'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => null,
                'minLength' => 4,
                'maxLength' => 4,
                'offset' => 12,
                'transparent' => true,
                'foreColor' => 0x269abc,
            ],
        ];
    }

    public function actionLangSwitch($lang = 'en-US')
    {
        $return = \common\components\Language::SetLanguage($lang);
        if ($return) {
            $this->redirect(Yii::$app->request->referrer);
        }
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $pageData = Page::findOne(2);
        return $this->render('page/index', [
            'pageData' => $pageData,
        ]);
    }

    public function actionFee()
    {
        $pageData = Page::findOne(5);
        return $this->render('page/page', ['pageData' => $pageData]);
    }

    public function actionShipping()
    {
        $pageData = Page::findOne(4);
        return $this->render('page/page', ['pageData' => $pageData]);
    }

    public function actionHelp()
    {
        $pageData = Page::findOne(7);
        return $this->render('page/page', ['pageData' => $pageData]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (isset($_REQUEST['returnurl'])) {
            Yii::$app->getSession()->set('returnUrl', $_REQUEST['returnurl']);
        } else if (Yii::$app->getUser()->getReturnUrl()) {
            Yii::$app->getSession()->set('returnUrl', Yii::$app->getUser()->getReturnUrl());
        }

        $this->layout = 'main_container';
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $SignUpModel = new SignupForm();
        $model = new LoginForm();

        # Registration
        if ($SignUpModel->load(Yii::$app->request->post())) {
            $password = $SignUpModel->password;
            if ($user = $SignUpModel->signup()) {
                $SignUpModel->sendEmail($password);
                Yii::$app->session->setFlash('success', TBase::ShowLbl('REGISTRATION_SUCCESSFULLY'));
	            return $this->redirect(['/registration-complete']);
            }
        }

        # Login
        $model->type = 'user';
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

        	$userModel = Yii::$app->user->identity;
	        $userModel->last_login = date('Y-m-d H:i:s');
	        $userModel->save(false);

            if (Yii::$app->getSession()->has('returnUrl')) {
                return $this->redirect(Yii::$app->getSession()->get('returnUrl'));
            } else {
                return $this->redirect(['user/my-page']);
            }
        } else {
            return $this->render('login', [
                'model' => $model,
                'signUpModel' => $SignUpModel,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $pageData = Page::findOne(6);
        $model = new ContactForm();
        $model->subject = TBase::ShowLbl('contact_us');
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', TBase::ShowLbl('CONTACT_US_MAIL_SENT'));
            } else {
                Yii::$app->session->setFlash('error', TBase::ShowLbl('CONTACT_MAIL_ERROR'));
            }

            return $this->refresh();
        } else {
            return $this->render('page/contact', [
                'model' => $model,
                'pageData' => $pageData
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        $pageData = Page::findOne(3);
        return $this->render('page/page', ['pageData' => $pageData]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionPage($slug)
    {
        $pageData = Page::findOne(['slug'=>$slug]);
        return $this->render('page/page', ['pageData' => $pageData]);
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = 'main_container';
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $password = $model->password;
            if ($user = $model->signup()) {

                $model->sendEmail($password);
                Yii::$app->session->setFlash('success', TBase::ShowLbl('REGISTRATION_SUCCESSFULLY'));
                return $this->redirect(['login']);
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'main_container';
        $model = new PasswordResetRequestForm();
        $model->type = 'user';
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', TBase::ShowLbl('CHECK_EMAIL_INSTRUCTION'));

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', TBase::ShowLbl('SORRY_PASSWORD_RESET_ERROR'));
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', TBase::ShowLbl('NEW_PASSWORD_SAVED'));

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }


    public function actionUserValidate($l, $t)
    {
        $user = User::findOne([
            'email' => base64_decode($l),
            'auth_key' => base64_decode($t),
            'status' => 9,
        ]);

        if ($user) {
            $user->status = 10;
            $user->auth_key = '';
            $user->save();
            Yii::$app->session->setFlash('success', TBase::ShowLbl('ACCOUNT_ACTIVATED_SUCCESS'));
            return $this->redirect(['login']);
        } else {
            Yii::$app->session->setFlash('danger', TBase::ShowLbl('INVALID_CREDENTIALS'));
            return $this->redirect(['login']);
        }
    }

    public function actionSearch($shop = null, $x = null)
    {
        if ($shop == 'auction') {
            if ($x == '') {
                return $this->redirect(Yii::$app->urlManager->createUrl(['yahoo-auctions/list']));
            }

frontend/views/site/connect.php
<?php
/*
// Request Token Endpoint
$req_url = 'https://auth.login.yahoo.co.jp/oauth/v2/get_request_token';
// AuthZ Endpoint
$authurl = 'https://auth.login.yahoo.co.jp/oauth/v2/request_auth';
// Access Token Endpoint
$acc_url = 'https://auth.login.yahoo.co.jp/oauth/v2/get_token';
// callback_url
$cbc_url = 'https://www.tanukishop.com/';
// sample API
$api_url = 'http://auctions.yahooapis.jp/AuctionWebService/V2/openWatchList';
// Consumerkey
$conskey = 'dj0zaiZpPWFHaGNEMUtTRFJvayZzPWNvbnN1bWVyc2VjcmV0Jng9MTk-';
// Consumersecret
$conssec = '3a10fbe08dfb2d6e4198dccd456b2e959504ce9a';
session_name("pecloauthyjp");
session_start();
if(isset($_GET['clear']) && $_GET['clear']==1){
  $_SESSION=array();
}
if(!isset($_GET['oauth_token']) && (isset($_SESSION['state']) && $_SESSION['state']==1)) {$_SESSION['state'] = 0;}
try {
  $oauth = new OAuth($conskey,$conssec,OAUTH_SIG_METHOD_HMACSHA1,OAUTH_AUTH_TYPE_URI);
  $oauth->enableDebug();
  if(!isset($_GET['oauth_token']) && !$_SESSION['state'] || $_SESSION['state']==0 ) {
    $request_token_info = $oauth->getRequestToken($req_url,$cbc_url);
    $_SESSION['secret'] = $request_token_info['oauth_token_secret'];
    $_SESSION['state'] = 1;
    header('Location: '.$authurl.'?oauth_token='.$request_token_info['oauth_token']);
    exit;
  } else if($_SESSION['state']==1) {
    $oauth->setToken($_GET['oauth_token'],$_SESSION['secret']);
    $access_token_info = $oauth->getAccessToken($acc_url,'',$_GET['oauth_verifier']);
    $token_res = var_export($access_token_info, true);
    $_SESSION['state'] = 2;
    $_SESSION['token'] = $access_token_info['oauth_token'];
    $_SESSION['secret'] = $access_token_info['oauth_token_secret'];
    $_SESSION['osh'] = $access_token_info['oauth_session_handle'];
    $_SESSION['guid'] = $access_token_info['xoauth_yahoo_guid'];
  }
  if(isset($_GET['refresh']) && $_GET['refresh']==1){
    // update Access Token
    $oauth->setToken($_SESSION['token'],$_SESSION['secret']);
    $access_token_info = $oauth->getAccessToken($acc_url, $_SESSION['osh']);
    $token_res = var_export($access_token_info, true);
  }
  // API Access
  $oauth->setToken($_SESSION['token'],$_SESSION['secret']);
  $oauth->fetch($api_url);
  $res = $oauth->getLastResponse();
} catch(OAuthException $E) {
  print_r($E);
}
?>
<html>
<head>
<title>PECL OAuth Library Sample with Yahoo! JAPAN</title>
</head>
<body>
<h1>PECL OAuth Library Sample with Yahoo! JAPAN</h1>
<a href="./">reload</a>
<a href="./?refresh=1">Access Token Refresh</a>
<a href="./?clear=1">restart</a>
<p>Access Token Response : </p>
<pre><?php echo htmlspecialchars(@$token_res); ?></pre>
<p>API Response : </p>
<pre><?php echo htmlspecialchars(@$res); ?></pre>
</body>
*/
?>

<?php
/**
 * Example of making API calls for the Yahoo service
 *
 * @author     Pieter Hordijk <info@pieterhordijk.com>
 * @copyright  Copyright (c) 2014 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */
use OAuth\OAuth1\Service\Yahoo;
use OAuth\Common\Storage\Session;
use OAuth\Common\Consumer\Credentials;
/**
 * Bootstrap the example
 */
$cbc_url = 'https://www.tanukishop.com/';
// sample API
$api_url = 'http://auctions.yahooapis.jp/AuctionWebService/V2/openWatchList';
// Consumerkey
$conskey = 'dj0zaiZpPWFHaGNEMUtTRFJvayZzPWNvbnN1bWVyc2VjcmV0Jng9MTk-';
// Consumersecret
$conssec = '3a10fbe08dfb2d6e4198dccd456b2e959504ce9a';
// Session storage
$storage = new Session();
// Setup the credentials for the requests
$credentials = new Credentials(
    $conskey,
    $conssec,
    $currentUri->getAbsoluteUri()
);
// Instantiate the Yahoo service using the credentials, http client and storage mechanism for the token
$yahooService = $serviceFactory->createService('Yahoo', $credentials, $storage);
if (!empty($_GET['oauth_token'])) {
    $token = $storage->retrieveAccessToken('Yahoo');
    // This was a callback request from Yahoo, get the token
    $yahooService->requestAccessToken(
        $_GET['oauth_token'],
        $_GET['oauth_verifier'],
        $token->getRequestTokenSecret()
    );
    // Send a request now that we have access token
    $result = json_decode($yahooService->request('profile'));
    echo 'result: <pre>' . print_r($result, true) . '</pre>';
} elseif (!empty($_GET['go']) && $_GET['go'] === 'go') {
    // extra request needed for oauth1 to request a request token :-)
    $token = $yahooService->requestRequestToken();
    $url = $yahooService->getAuthorizationUri(array('oauth_token' => $token->getRequestToken()));
    header('Location: ' . $url);
} else {
    $url = $currentUri->getRelativeUri() . '?go=go';
    echo "<a href='$url'>Login with Yahoo!</a>";
}

frontend/views/site/cost.php
<?php
    use \common\components\TBase;
    $model = new \common\components\TCurrencyConvertor;
?>

<style>
    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th {
        padding: 3px;
    }
    .table {  margin-bottom: 4px;  }
    .recommend{color:#df7b2b;}
    th.text-center{background-color:#df7b2b;color:#fff;padding: 8px!important; }
</style>
<p class="recommend"><?=TBase::ShowLbl('RECOMMENDED');?>:</p>
<table class="table-striped table">
    <tr>
        <th class="text-center"><?=TBase::ShowLbl('PRICE')?></th>
        <th class="text-center"><?=TBase::ShowLbl('QTY')?></th>
        <th class="text-center"><?=TBase::ShowLbl('TANUKI_CHARGES')?></th>
        <th class="text-center"><?=TBase::ShowLbl('shipping')?></th>
        <th class="text-center"><?=TBase::ShowLbl('TOTAL')?></th>
    </tr>
<?php

foreach($result as $key => $list) {
    if ($key == 0) {
        echo '<tr style="font-weight: bold;">';
    } else {
        echo '<tr>';
    }
	$language_id = Yii::$app->request->post('language_id');
	$language = ($language_id) ? $language_id : 'JPY';
	$amount = ((($data['price']*(int)$data['quantity'])+(int)$list['cost']+$data['tanuki_charge']));
    ?>
        <td class="text-center" style="width: 14%! important"><?=\common\models\CurrencyTable::convert($data['price'],'JPY',$language)?> </td>
        <td class="text-center" style="width:7%"><?=$data['quantity']?></td>
        <td class="text-center" style="width:19%"><?=\common\models\CurrencyTable::convert($data['tanuki_charge'],'JPY',$language);?></td>
        <td class="text-center">(<?=$list->method->title; ?>): <?=\common\models\CurrencyTable::convert($list['cost'],'JPY',$language)?> </td>

        <td class="text-center" style="color:#df7b2b;"><?=\common\models\CurrencyTable::convert($amount,'JPY',$language)?> </td>
    </tr>
<?php
}
?>
</table>
<?=\yii\bootstrap\Html::a(TBase::ShowLbl('MORE_ABOUT_INTERNATIONAL_SHIPPING'),['/site/shipping'],['style'=>"color:#df7b2b;"])?>

frontend/views/site/cost_category.php
<?php
    use \common\components\TBase;
    use \common\models\CurrencyTable;
    ?>

<style>
    .table>tbody>tr>td,.table>tbody>tr>th,.table>tfoot>tr>td,.table>tfoot>tr>th,.table>thead>tr>td,.table>thead>tr>th{padding:7px;font-size:15px}.table{margin-bottom:4px}.recommend{color:#df7b2b}th.text-center{background-color:#df7b2b;color:#fff;padding:8px!important}.ibox-content{clear:both;background-color:#fff;color:inherit;padding:15px 20px 20px;border-color:#e7eaec;border-image:none;border-style:solid solid none;border-width:1px 0}
    #item-shipping-calculation_category .ibox-content {
        border: none;
    }
</style>
<?php
$Fprice = 0;

$Fprice = ($result->weight_base ==0) ? $result->international_shipping_cost : ($data['package_weight']*$result->international_shipping_cost);
$total =0;
$optionCharge = ($data['option']==1)?TBase::TanukiSetting('Category_shipping_option_1'):TBase::TanukiSetting('Category_shipping_option_2');
$total = $data['price'] + $result->delivery_in_japan_cost + $result->tanuki_fee + $Fprice + $optionCharge;

?>
<div class="ibox-content">
<table class="table-striped table notranslate">
    <tr>
        <td ><?=TBase::ShowLbl('PRICE')?></td>
        <td ><?=CurrencyTable::convert($data['price'],'JPY','JPY'); ?></td>
        <td ><?=CurrencyTable::convert($data['price'],'JPY','RUB'); ?></td>
    </tr>
    <tr>
        <td ><?=TBase::ShowLbl('Shipping_in_japan')?></td>
        <td ><?=CurrencyTable::convert($result->delivery_in_japan_cost,'JPY','JPY'); ?></td>
        <td ><?=CurrencyTable::convert($result->delivery_in_japan_cost,'JPY','RUB'); ?></td>
    </tr>
    <tr>
        <td ><?=TBase::ShowLbl('TANUKI_CHARGES')?></td>
        <td ><?=CurrencyTable::convert($result->tanuki_fee,'JPY','JPY'); ?></td>
        <td ><?=CurrencyTable::convert($result->tanuki_fee,'JPY','RUB'); ?></td>
    </tr>
    <tr>
        <td ><?=TBase::ShowLbl('International_shipping_label')?></td>
        <td ><?=CurrencyTable::convert($Fprice,'JPY','JPY'); ?></td>
        <td ><?=CurrencyTable::convert($Fprice,'JPY','RUB'); ?></td>
    </tr>
    <tr>
        <td ><?=TBase::ShowLbl('Option_label')?></td>
        <td ><?=($data['option']==1)?CurrencyTable::convert(TBase::TanukiSetting('Category_shipping_option_1'),'JPY','JPY'):CurrencyTable::convert(TBase::TanukiSetting('Category_shipping_option_2'),'JPY','JPY');  ?></td>
        <td ><?=($data['option']==1)?CurrencyTable::convert(TBase::TanukiSetting('Category_shipping_option_1'),'JPY','RUB'):CurrencyTable::convert(TBase::TanukiSetting('Category_shipping_option_2'),'JPY','RUB');  ?></td>
    </tr>
    <tr>
        <td><strong><?=TBase::ShowLbl('ИТОГО')?></strong></td>
        <td ><?=CurrencyTable::convert($total,'JPY','JPY'); ?></td>
        <td ><?=CurrencyTable::convert($total,'JPY','RUB'); ?></td>
    </tr>
</table>
    </div>
<?=\yii\bootstrap\Html::a(TBase::ShowLbl('MORE_ABOUT_INTERNATIONAL_SHIPPING'),['/site/shipping'],['style'=>"color:#df7b2b;"])?>

frontend/views/site/error.php
<?php
$lang = \common\components\TBase::CLang();
$pageData = \common\models\Page::findOne(17);
$this->title = ($lang == 'en-US') ? $pageData->title_en : $pageData->title_ru;

$this->registerMetaTag(['name' => 'title', 'content' => $pageData->meta_title]);
$this->registerMetaTag(['name' => 'description', 'content' => $pageData->meta_desc]);
$this->registerMetaTag(['name' => 'keywords', 'content' => $pageData->meta_keywords]);

?>
    <div class="container page notranslate">
        <h3 class="about-head"><?=$this->title; ?></h3>
        <ol class="breadcrumb"></ol>
		<?=($lang == 'en-US') ? $pageData->detail_en : $pageData->detail_ru; ?>
    </div>
<?php
$this->registerCss("
.container.page{
min-height:300px;
margin-top: 19px;
}
.container.page ul li{
    margin-left: 25px;
}
");
?>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
USE \common\components\TBase;
$this->title = TBase::ShowLbl('SIGN_UP_LOGIN');
$this->params['breadcrumbs'][] = $this->title;

?>
<section class="notranslate">
    <div class="container">
        <h3 style="text-align:center;" class="heading_bg"><span><?=TBase::ShowLbl('SIGN_UP_LOGIN')?></span></h3>
        <div class="row">
            <div class="col-sm-6">
                <div class="col-sm-12 mt20">
                    <div class="col-sm-6"><h3 class="reg-h1"><?=TBase::ShowLbl('REGISTER')?></h3></div>
                    <div class="col-sm-6 mt10 txt-r"><span class="star">*</span><?=TBase::ShowLbl('REQUIRED_FIELD')?></div>
                    <div class="clearfix"></div>
                    <?php $form = ActiveForm::begin([
                        'id' => 'form-signup',
                        'options' => [
                            'onsubmit' => "yaCounter48497555.reachGoal ('registrationtanuki'); return true;"
                        ]

                    ]); ?>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'first_name')->textInput() ?>
                        </div>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'last_name')->textInput() ?>
                        </div>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'password')->passwordInput() ?>
                        </div>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'confirmPassword')->passwordInput() ?>
                        </div>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'email') ?>
                        </div>
                        <div class="col-sm-6 reg-form">
                            <?= $form->field($signUpModel, 'language')->dropDownList(['en-US'=>'English','ru-RU'=>'Russian']) ?>
                        </div>

                        <div class="col-sm-12 reg-form">
                            <?= $form->field($signUpModel, 'captcha')->widget(\yii\captcha\Captcha::classname(), [
                                'template' => '<div class="">{image} <a href="javascript:;" id="fox">'.TBase::ShowLbl('REFRESH').'</a></div><div class="">{input}</div>',
                                'captchaAction'=>'site/captcha',
                            ])?>

                        </div>
                        <div class="col-sm-12">
                            <?php echo $form->field($signUpModel, 'terms', ['options' => ['tag' => 'span',], 'template' => "{input}"])->checkbox(['checked' => false,'class'=>'mr10']);?>
                        </div>
                        <div class="col-sm-12 mt20"><label ></label>
                            <?= Html::submitButton(TBase::ShowLbl('CREATE_ACCOUNT'), ['class' => 'btn btn-info register', 'name' => 'register-button']) ?>
                        </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
            <div class="col-sm-1 c-line">
                <?=Html::img('@web/tnk/images/center-line.jpg') ?>
            </div>
            <div class="col-sm-5">
                <div class="col-sm-12 mt100">
                    <div class="col-sm-12"><h3 class="reg-h1"><?=TBase::ShowLbl('ALREADY_ACCOUNT')?></h3></div>
                    <?php $form = ActiveForm::begin([
                        'id' => 'login-form',
                    ]); ?>
                        <div class="col-sm-12 reg-form">
                            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                        </div>
                        <div class="col-sm-12 reg-form">
                            <?= $form->field($model, 'password')->passwordInput() ?>
                        </div>
                        <div class="col-sm-6">
                            <?= $form->field($model, 'rememberMe')->checkbox(['class'=>'mr10']) ?>
                        </div>
                        <div class="col-sm-6 txt-r"><?= Html::a(TBase::ShowLbl('FORGET_PASSWORD'), ['site/request-password-reset']) ?></div>
                        <div class="col-sm-12 mt20">
                            <label ></label>
                            <?= Html::submitButton(TBase::ShowLbl('LOGIN'), ['class' => 'btn btn-info login', 'name' => 'login-button']) ?>
                        </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
$this->registerJs('
    $(document).ready(function () {
        $("#fox").click(function (event) {
            event.preventDefault();
            $(this).parent().children(\'img\').click();
        })
    });
    ');

$this->registerJs('
    $("#signupform-first_name").focus();
    ',yii\web\View::POS_READY);

$this->registerCss('
.reg-form{position:relative;}
.help-block-error{position: absolute;text-align: right;right: 14px;}
');

?>